imports:
  - { resource: ./presenters.yml }

services:
  _defaults:
    public: true

  ps_edition_basic.module:
    class: ps_edition_basic
    factory: ["Module", "getInstanceByName"]
    arguments:
      - "ps_edition_basic"

  ps_edition_basic.ps_accounts.installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - "5.2.5"

  ps_edition_basic.ps_accounts.facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - "@ps_edition_basic.ps_accounts.installer"

  PrestaShop\Module\PsEditionBasic\Service\ModuleService:
    class: PrestaShop\Module\PsEditionBasic\Service\ModuleService
    arguments:
      - "@prestashop.module.manager"
      - "@=service('ps_edition_basic.module').name"
      - "@=service('ps_edition_basic.module').addons_id"
