/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PuikAlert: typeof import('@prestashopcorp/puik/es')['PuikAlert']
    PuikButton: typeof import('@prestashopcorp/puik/es')['PuikButton']
    PuikCard: typeof import('@prestashopcorp/puik/es')['PuikCard']
    PuikCheckbox: typeof import('@prestashopcorp/puik/es')['PuikCheckbox']
    PuikIcon: typeof import('@prestashopcorp/puik/es')['PuikIcon']
    PuikLink: typeof import('@prestashopcorp/puik/es')['PuikLink']
    PuikModal: typeof import('@prestashopcorp/puik/es')['PuikModal']
    PuikProgressBar: typeof import('@prestashopcorp/puik/es')['PuikProgressBar']
    PuikSkeletonLoader: typeof import('@prestashopcorp/puik/es')['PuikSkeletonLoader']
    PuikSkeletonLoaderGroup: typeof import('@prestashopcorp/puik/es')['PuikSkeletonLoaderGroup']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
