name: "Publish Module Update"
description: "Publish PrestaShop module on the marketplace"

inputs:
  marketplace-api-key:
    description: "Marketplace API key"
    required: true
  zip:
    description: "ZIP file"
    required: true
  id-product:
    description: "Product ID"
    required: true
  technical-name:
    description: "Technical name"
    required: true
  display-name:
    description: "Display name"
    required: true
  change-log:
    description: "Change log"
    required: true
  channel:
    description: "Channel"
    required: false
    default: stable
  type-upgrade:
    description: "Type upgrade"
    required: false
    default: updatemin
  compatible-from:
    description: "Compatible from"
    required: true

outputs:
  published-version:
    description: "Latest version published to marketplace, based on `last_release.product_version`"
    value: ${{ steps.get-published-version.outputs.published-version }}

runs:
  using: composite

  steps:
    - id: publish-module-update
      shell: bash
      run: |
        curl --silent --location --request POST 'https://api.addons.prestashop.com/request/index.php?method=module_push' \
          --header "api-key: $MARKETPLACE_API_KEY" \
          --form "zip=@$ZIP" \
          --form "id_product=$ID_PRODUCT" \
          --form "technical_name=$TECHNICAL_NAME" \
          --form "display_name=$DISPLAY_NAME" \
          --form "change_log=$CHANGE_LOG" \
          --form "channel=$CHANNEL" \
          --form "type_upgrade=$TYPE_UPGRADE" \
          --form "product_type=module" \
          --form "compatible_from=$COMPATIBLE_FROM" \
          --include
      env:
        MARKETPLACE_API_KEY: ${{ inputs.marketplace-api-key }}
        ZIP: ${{ inputs.zip }}
        ID_PRODUCT: ${{ inputs.id-product }}
        TECHNICAL_NAME: ${{ inputs.technical-name }}
        DISPLAY_NAME: ${{ inputs.display-name }}
        CHANGE_LOG: ${{ inputs.change-log }}
        CHANNEL: ${{ inputs.channel }}
        TYPE_UPGRADE: ${{ inputs.type-upgrade }}
        COMPATIBLE_FROM: ${{ inputs.compatible-from }}

    - id: get-published-version
      shell: bash
      run: |
        PUBLISHED_VERSION=$(curl --silent --location --request POST 'https://api.addons.prestashop.com/request/index.php?method=product' \
          --header "api-key: $MARKETPLACE_API_KEY" \
          --form "id_product=$ID_PRODUCT" \
          | jq -r '.product.technical_info.last_release.product_version')
        echo "published-version=$PUBLISHED_VERSION" >> "$GITHUB_OUTPUT"
      env:
        MARKETPLACE_API_KEY: ${{ inputs.marketplace-api-key }}
        ID_PRODUCT: ${{ inputs.id-product }}
