# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: ci

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

env:
  PHP_VERSION: 8.1

jobs:
  php-linter:
    name: PHP Syntax check 8.1 => 8.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master
      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.1@master
      - name: PHP syntax checker 8.3
        uses: prestashop/github-action-php-lint/8.1@master

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{env.PHP_VERSION}}

      - name: Validate
        run: |
          composer validate --strict

      - name: Format
        run: |
          composer php-cs-fixer

      - name: Lint
        run: |
          composer php-lint

      - name: Test
        run: |
          composer unit-tests
