name: PHP
on: [push, pull_request]

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PHP_VERSION: 8.1

jobs:
  php-linter:
    name: PHP Syntax check 8.1 => 8.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master
      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@master
      - name: PHP syntax checker 8.3
        uses: prestashop/github-action-php-lint/8.3@master
      - name: PHP syntax checker 8.4
        uses: prestashop/github-action-php-lint/8.4@master

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: tleon/.github/actions/php-ci/php-cs@Issue-39300-improve-module-ci
        with:
          php-version: ${{ env.PHP_VERSION }}

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Composer Install
        run: COMPOSER_PROCESS_TIMEOUT=600 composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Run Unit Tests
        run: composer unit-tests

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta_version: ['9.0.x']
        php_version: ['8.1', '8.2', '8.3']
      fail-fast: false
    steps:
      - uses: tleon/.github/actions/php-ci/phpstan@Issue-39300-improve-module-ci
        with:
          php-version: ${{ matrix.php_version }}
          presta-version: ${{ matrix.presta_version }}
          module-name: ps_classic_edition
          phpstan-config: tests/phpstan/phpstan-${{ matrix.presta_version }}.neon
